### ISSUE TITLE
Issue with GRCh38 Reference in DeltaSplice

### ISSUE THREAD

**Issue by ToolForVol** [chaolinzhanglab/DeltaSplice#5]
Dear Prof. Zhang,

Sorry to bother you. I’ve been using DeltaSplice, and it’s very impressive. However, I’ve encountered an issue when testing a VCF input with the **GRCh38 reference** with option **-U=1**.

- When I run the following command:

```bash
deltasplice -I my_input/test_hg38_10.vcf -O my_output/test.vcf -R data/genomes/hg38.fa  -A grch38 -U 1 -M 0
``` 

- It occurs a problem:

![image](https://github.com/user-attachments/assets/352b0d33-b3f0-409f-a540-2fc08aaebe2f)

- I get an error. Upon inspecting the default reference by output the keys of annotator.sortedKeys, it seems there is no entry for hg38.

Could you clarify if I am missing something, or if there is a specific way to retrieve output based on the GRCh38 reference using default reference sequences?
Thank you for your help!

Best regards:)

**Comment by Zoesgithub** [comment]
The problem is caused by missing of hg38.fa file, so please run "bash Tools/download_files.sh" before running the inference process. The script will prepare necessary files.

**Comment by ToolForVol** [comment]
Dear Prof. Zhang,
Thank you for your response! I will give it a try.
